<?php

namespace App\Model;

use App\Model;

class TestModel extends Model
{
    public function __init()
    {
        // parent::__init(); // TODO: Change the autogenerated stub
    }

    function index()
    {
        return self::$db->where('id', 2)->find();
    }
}