<?php

namespace App\Controller;

use App\Controller;


class IndexController extends Controller
{
    public function __init()
    {
        // parent::__init(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $param = $this->_request->input();
        $this->_view->assign('title', $param['title']);
        $this->_view->assign('content', $param['content']);
        $this->_view->display('index.html');

    }

    public function register()
    {
        echo 'This is register';
    }

}