<?php

namespace App\Controller;

use App\Controller;
use App\Model\TestModel;


class IndexController extends Controller
{
    public function __init()
    {
        // parent::__init();// TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->_view->display('index.html');
    }

    public function test()
    {
        $model = new TestModel('user');
        echo '<pre>'; print_r($model->index());
    }

}