<?php

namespace App\Controller;

use App\Controller;


class IndexController extends Controller
{
    public function __init()
    {
        // parent::__init();// TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->_view->display('index.html');
    }

}